version: "3.9"
services:
  kltn-fe-admin:
    image: kltn-fe-admin:${IMAGE_VERSION}
    ports:
      - "4051:80"
    container_name: kltn-fe-admin
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 50M
    restart: unless-stopped
    env_file:
      - .env
